# Generated by Django 2.1.4 on 2018-12-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculate', models.CharField(max_length=4)),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('c', models.TextField()),
            ],
        ),
    ]
